# Generated by Django 4.2.1 on 2025-08-04 10:55

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_onetimevideotoken_wpactionscheduleractions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneTimeReWatchToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('user_id', models.IntegerField()),
                ('message_id', models.CharField(max_length=50)),
                ('video_id', models.CharField(max_length=100)),
                ('video_caption', models.CharField(max_length=500)),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('meta_data', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'one_time_rewatch_tokens',
                'indexes': [models.Index(fields=['token'], name='one_time_re_token_c98c91_idx'), models.Index(fields=['user_id', 'message_id'], name='one_time_re_user_id_9516db_idx'), models.Index(fields=['is_used'], name='one_time_re_is_used_38b622_idx')],
            },
        ),
    ]
