# Generated by Django 4.2.1 on 2025-08-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_onetimerewatchtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseReminderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_30_min_enabled', models.BooleanField(default=True)),
                ('reminder_6_hour_enabled', models.BooleanField(default=True)),
                ('max_6_hour_reminders', models.IntegerField(default=3)),
                ('dnd_start_time', models.TimeField(default='20:00:00')),
                ('dnd_end_time', models.TimeField(default='08:00:00')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'course_reminder_settings',
            },
        ),
        migrations.CreateModel(
            name='UserReminderPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('enable_30_min_reminder', models.BooleanField(default=True)),
                ('enable_6_hour_reminder', models.BooleanField(default=True)),
                ('custom_dnd_start', models.TimeField(blank=True, null=True)),
                ('custom_dnd_end', models.TimeField(blank=True, null=True)),
                ('timezone_offset', models.IntegerField(default=0)),
                ('max_reminders_per_day', models.IntegerField(default=5)),
                ('last_reminder_sent', models.DateTimeField(blank=True, null=True)),
                ('total_reminders_sent', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_reminder_preferences',
            },
        ),
        migrations.CreateModel(
            name='CourseReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('course_id', models.IntegerField()),
                ('reminder_type', models.CharField(choices=[('30_min', '30 Minutes'), ('6_hour', '6 Hours'), ('admin', 'Admin Triggered')], max_length=10)),
                ('message_id', models.CharField(default='', max_length=20)),
                ('scheduled_time', models.DateTimeField()),
                ('sent_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped_dnd', 'Skipped - Do Not Disturb'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('phone_number', models.CharField(default='', max_length=20)),
                ('user_name', models.CharField(default='', max_length=100)),
                ('course_name', models.CharField(default='', max_length=255)),
                ('reminder_count', models.IntegerField(default=0)),
                ('triggered_by', models.CharField(default='system', max_length=50)),
                ('error_message', models.TextField(blank=True)),
                ('meta_data', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'course_reminder_logs',
                'indexes': [models.Index(fields=['user_id', 'course_id'], name='course_remi_user_id_b05567_idx'), models.Index(fields=['scheduled_time', 'status'], name='course_remi_schedul_4569ed_idx'), models.Index(fields=['reminder_type', 'status'], name='course_remi_reminde_49bded_idx')],
            },
        ),
    ]
