# Generated by Django 4.2.1 on 2025-08-08 06:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_courseremindersettings_userreminderpreference_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onetimevideotoken',
            old_name='accessed_at',
            new_name='used_at',
        ),
        migrations.AddField(
            model_name='onetimevideotoken',
            name='meta_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='onetimerewatchtoken',
            name='video_caption',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='onetimerewatchtoken',
            name='video_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='onetimevideotoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='onetimevideotoken',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='onetimevideotoken',
            name='user_phone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='onetimevideotoken',
            name='video_id',
            field=models.CharField(max_length=255),
        ),
    ]
