# Generated by Django 4.2.1 on 2025-08-11 11:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_accessed_at_onetimevideotoken_used_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimerewatchtoken',
            name='used_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
