# Generated by Django 4.2.1 on 2025-08-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_onetimerewatchtoken_used_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimerewatchtoken',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
